// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://serbsrbtlembxzzkkdcx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlcmJzcmJ0bGVtYnh6emtrZGN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYxNjY4MzcsImV4cCI6MjA5MTc0MjgzN30.xgB1F2XtqGurwm2WlI_7eVRryC016POFg-rwrVBZ92Q";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});